blank_issues_enabled: true
contact_links:
  - name: Tyler Boswick
    url: redlineperf.com
    about: Tell me what ails you
  - name: Joe Somebody
    url: thatwasamovie.com
    about: Was Tim Allen really ever talented?